import type { CRMRecord } from "./types";

function iso(daysAgo: number): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
}

export function seedRecords(): CRMRecord[] {
  return [
    {
      id: crypto.randomUUID(),
      createdAt: iso(2),
      client: "أحمد بن صالح",
      phone: "0612345678",
      zone: "حي السلام، الدار البيضاء",
      brand: "Saunier Duval",
      model: "Themaplus Condens",
      serviceType: "boiler",
      installationLocation: "home",
      boilerAction: "repair",
      status: "waiting",
      finalState: "enRoute",
      fault: "Code F.28 — pas d'allumage. التشخيص الأولي: مشكل في الإلكترود.",
      assignedTech: "Karim",
      payment: { partsCost: 450, laborCost: 300, advance: 200 },
      warranty: { status: "out", company: "Saunier Duval Maroc", serial: "SD-2021-887" },
      visits: [],
      visitNumber: 1,
      inDailyPlan: true,
      appointment: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
      tasks: [],
    },
    {
      id: crypto.randomUUID(),
      createdAt: iso(120),
      completionDate: iso(118),
      client: "فاطمة الزهراء",
      phone: "0698765432",
      zone: "أنفا، الدار البيضاء",
      brand: "Vaillant",
      model: "ecoTEC plus",
      serviceType: "boiler",
      installationLocation: "home",
      boilerAction: "maintenance",
      status: "done",
      fault: "Entretien annuel — détartrage échangeur.",
      diagnosticFinal: "Détartrage complet, anode remplacée, pression réajustée à 1.5 bar.",
      assignedTech: "Younes",
      payment: { partsCost: 0, laborCost: 600, advance: 600 },
      warranty: { status: "under", company: "Vaillant France", serial: "VL-2024-1129", startDate: iso(400).slice(0, 10), endDate: iso(-330).slice(0, 10) },
      visits: [],
      visitNumber: 1,
      inDailyPlan: false,
      archivedAt: iso(118),
      tasks: [],
    },
    {
      id: crypto.randomUUID(),
      createdAt: iso(5),
      client: "فاطمة الزهراء",
      phone: "0698765432",
      zone: "أنفا، الدار البيضاء",
      brand: "Vaillant",
      model: "ecoTEC plus",
      serviceType: "boiler",
      installationLocation: "home",
      boilerAction: "repair",
      status: "waiting",
      finalState: "awaitingParts",
      fault: "Code F75 — pompe ne s'amorce pas après détartrage.",
      payment: { partsCost: 850, laborCost: 250 },
      warranty: { status: "under", company: "Vaillant France", serial: "VL-2024-1129" },
      visits: [],
      visitNumber: 2,
      inDailyPlan: false,
      tasks: [],
    },
    {
      id: crypto.randomUUID(),
      createdAt: iso(0),
      client: "محمد العلوي",
      phone: "0655443322",
      zone: "حي المحمدي، الرباط",
      brand: "",
      model: "",
      serviceType: "plumbing",
      installationLocation: "home",
      status: "waiting",
      fault: "تسرب ماء تحت المغسلة في المطبخ.",
      payment: { partsCost: 80, laborCost: 200, advance: 280 },
      visits: [],
      visitNumber: 1,
      inDailyPlan: true,
      tasks: [
        { id: crypto.randomUUID(), text: "فحص أنبوب التصريف", done: true },
        { id: crypto.randomUUID(), text: "تعويض الجوان", done: false },
        { id: crypto.randomUUID(), text: "اختبار الضغط", done: false },
      ],
    },
    {
      id: crypto.randomUUID(),
      createdAt: iso(10),
      client: "Société Atlas Immobilier",
      phone: "0522112233",
      zone: "Quartier industriel, Casablanca",
      brand: "Bosch",
      model: "Condens 5000 W",
      serviceType: "boiler",
      installationLocation: "workshop",
      boilerAction: "install",
      status: "waiting",
      finalState: "enRoute",
      fault: "Installation neuve d'une chaudière murale 28 kW.",
      assignedTech: "Karim",
      payment: { partsCost: 18000, laborCost: 4500, advance: 10000 },
      warranty: { status: "under", company: "Bosch Thermotechnologie", serial: "BS-2026-441", startDate: iso(10).slice(0, 10), endDate: iso(-720).slice(0, 10) },
      visits: [],
      visitNumber: 1,
      inDailyPlan: false,
      tasks: [],
    },
  ];
}
